apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: grafana-g1
  namespace: monitoring
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: zws.grafana.baway.org.cn
  routes:
  - conditions:
    - prefix: /
    services:
    - name: grafana
      port: 3000
#  ingressClassName: nginx
