apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-zws
  namespace: zws
provisioner: nfs-diy-private # 和 deployment.yaml 中 env.PROVISIONER_NAME 保持一致
reclaimPolicy: Retain
parameters:
  archiveOnDelete: "false"
