apiVersion: v1
kind: Service
metadata:
  namespace: zws
  labels:
    app: mysql
  name: zwsmysql
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
