apiVersion: v1
kind: PersistentVolume
metadata:
  name: zws-pv
  namespace: zws
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.27.3.140  # 设置NFS服务器地址
    path: /share                    # 设置NFS服务器上的挂载路径
  storageClassName: zws

