apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conf-pvc
  namespace: zws
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi             # 设置PVC的存储大小
  storageClassName: nfs-zws

