apiVersion: v1
kind: Service
metadata:
  namespace: zws
  labels:
    app: demo
  name: zwsweb
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo
